version: "3"
services:
  devcontainer-svelte-5-template:
    container_name: devcontainer-svelte-5-template
    build: .
    environment:
      - NODE_ENV=production
      - "PORT=3005"
    ports:
      - 3005:3005
    # volumes:
    #   - devcontainer-svelte-5-template:/home/node/app
    restart: unless-stopped

# volumes:
#   devcontainer-svelte-5-template:
