version: "3.9"
services:
  devcontainer-svelte-5-template:
    container_name: devcontainer-svelte-5-template
    build: .
    working_dir: /workspaces
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://dev:devcontainer@postgres:5432/devcontainer_svelte_5_template
      # - GITHUB_CLIENT_ID=
      # - GITHUB_CLIENT_SECRET=
      # - GOOGLE_CLIENT_ID=
      # - GOOGLE_CLIENT_SECRET=
    volumes:
      - .:/workspaces:cached
      - dev-devcontainer-svelte-5-template:/workspaces
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devcontainer
      POSTGRES_DB: devcontainer_svelte_5_template
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  dev-devcontainer-svelte-5-template:
  postgres-data:
