version: "3.9"
services:
  devcontainer-svelte-5-template:
    container_name: devcontainer-svelte-5-template
    build: .
    working_dir: /workspaces
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - NODE_ENV=development
      # - DATABASE_URL=mongodb://dev:devcontainer@mongodb:27017/devcontainer-svelte-5-template
      # - GITHUB_CLIENT_ID=
      # - GITHUB_CLIENT_SECRET=
      # - GOOGLE_CLIENT_ID=
      # - GOOGLE_CLIENT_SECRET=
    volumes:
      - .:/workspaces:cached
      - dev-devcontainer-svelte-5-template:/workspaces
    depends_on:
      - mongodb

  mongodb:
    container_name: devcontainer-mongodb
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: devcontainer
    ports:
      - "27017:27017"
    volumes:
      - devcontainer-mongodb-data:/data/db

volumes:
  dev-devcontainer-svelte-5-template:
  devcontainer-mongodb-data:
