version: "3.9"
services:
  devcontainer-svelte-5-template:
    container_name: dev-devcontainer-svelte-5-template
    build: .
    working_dir: /workspaces
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/workspaces:cached
      - dev-devcontainer-svelte-5-template:/workspaces
    depends_on:
      - mongodb

  mongodb:
    container_name: dev-mongodb-devcontainer-svelte-5-template
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: devcontainer-svelte-5-template
    ports:
      - "27017:27017"
    volumes:
      - dev-mongodb-devcontainer-svelte-5-template-data:/data/db

volumes:
  dev-devcontainer-svelte-5-template:
  dev-mongodb-devcontainer-svelte-5-template-data:
