version: "3.9"
services:
  devcontainer-svelte-5-template:
    container_name: devcontainer-svelte-5-template
    build: .
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:3333

    working_dir: /app
    volumes:
      - ../:/app

volumes:
  dev-devcontainer-svelte-5-template:
